version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env.production
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - db
    command: >
      sh -c "
        chmod +x ./wait-for-it.sh &&
        ./wait-for-it.sh db:3306 -- \
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run start:prod
      "

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
    container_name: frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Laura0824
      MYSQL_DATABASE: datodo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
